### ISSUE TITLE
[Feature] Expose urgency to allow styling

### ISSUE THREAD

**Issue by GallowsDove** [Dr-42/end-rs#11]
Expose notification urgency to Eww to allow different styling. This could be done for example via classes on boxes.

**Comment by Dr-42** [comment]
How would this work in your opinion? Like will the user create different notification widgets which I append to the list and specify different classes to them?

This would make more visually pleasing notifs, but also has the risk of increasing clutter.

Can you please create a minimum example?

Thank you in advance.

**Comment by GallowsDove** [comment]
In my mind, you could probably just add another class to the outer box of `defwidget end-notification[notification]`, e.g.

```
(box
      :class "end-default-notification-box notification-urgency-${notification.urgency}"
      :orientation "horizontal"
      :space-evenly false
      (image
      .......
```

then you might style it with:

```
.end-default-notification-box.notification-urgency-low {
    // CSS HERE, e.g. border color
}
```

This is also extendable, and user might modify and add urgency class to whatever he wishes to style.

**Comment by Dr-42** [comment]
I have exposed the urgency field as a string in this commit. Check if it works.

Also if possible can update the examples and README? Both the app_name feature and the urgency flags stand somewhat left out in the examples and README.

**Comment by GallowsDove** [comment]
I'll can look into it in a few days when I'll have time.

**Comment by Dr-42** [comment]
I had some free time today so I added all the documentation and updated the defaults. Closing as completed.
