### ISSUE TITLE
Escape quotes in notification fields

### ISSUE THREAD

**Issue by GallowsDove** [Dr-42/end-rs#15]
I've noticed the following eww error in journalctl:

```
error: Failed to turn `{"actions":"[{\"id\":\"default\",\"text\":\"View\"}]","application":"vesktop","body":"Reacted 🤣 to you "test message"","icon":"","app_icon":"/usr/share/icons/hicolor/64x64/apps/vesktop.png","id":"1498","summary":"User (#shame-room, Prime Gaming Group)","urgency":"normal"}` into a value of type json-value
```

I believe the issue is that there are unescaped quotes in
```
"body":"Reacted 🤣 to you "test message""
```
I believe quotes should be escaped to not fail when there are quotes in notification body or summary

**Comment by Dr-42** [comment]
I just gave up and replaced quotes with their ascii to avoid any conflicts. Let's hope it sticks. I also removed the manual eww_val build and employes serde_json as we were already using it.
