### ISSUE TITLE
getcss undefined?

### ISSUE THREAD

**Issue by juanolon** [Dr-42/end-rs#2]
Hi, i was about to try end-rs, but after generating the yuck/css file, i get the error:

```
error: No variable named `getcss` in scope
    ┌─ end.yuck:113:12
    │
113 │       :css getcss
    │            ────── Used here
```
I haven't found `getcss` defined anywhere in the repository..

**Comment by Dr-42** [comment]
That is an artifact from my own dotfiles as I am using a python script to generate css to sync the colors of all the eww widgets with my wallpaper. You can safely remove it and it would work. I will fix it in this repo as soon as possible.
