### ISSUE TITLE
Daemon randomly hangs

### ISSUE THREAD

**Issue by GaspardCulis** [Dr-42/end-rs#3]
Haven't found a way to reproduce this bug, bug sometimes the end-rs daemon will just stop to display notifications and all `notify-send` calls will hang forever (the daemon process is still running). This is really frustrating and when this occurs I have to restart the daemon. Am I the only one to have this issue ?

**Comment by Dr-42** [comment]
I have experienced this one or two times too, but like you, I am unable to reproduce this. I suspected it has something to do with eww calls. But without any debug info, it is hard to pin it down.

Maybe we can add verbose logging to all of the daemon's actions and then diagnose it by that.

**Comment by GallowsDove** [comment]
@Dr-42 this is still happening for me on 0.1.14, I don't think it has been solved. To reproduce, just keep sending `notify-send "hello"`, usually hangs within 10 notifications

**Comment by Dr-42** [comment]
I see. I guess I need to add the logging thing and catch where the daemon hangs.

**Comment by Dr-42** [comment]
I added logging. The program now logs at /tmp/end.log.

The thing I noticed is that sometimes, the body is not being passed up to the daemon. So maybe this is a zbus issue? If so, I think upgrading to zbus 5 might help as it the latest version. 

I am not entirely sure though if it is a zbus issue. If somebody might verify that it is a zbus issue that would be helpful.

**Comment by Dr-42** [comment]
I believe the icon loader was causing the hangups. Please test 0.1.16

**Comment by GallowsDove** [comment]
@Dr-42 not sure what you did but on 0.1.16, latest master, it doesn't load even one notification and just hangs instantly. `notify-send "hello"` just hangs.

**Comment by Dr-42** [comment]
Can you post the contents of /tmp/end.log

That is the log file I added

**Comment by GallowsDove** [comment]
Yeah I've made a new issue for it, #12

**Comment by Dr-42** [comment]
The freeze happens when the icon loader hangs. I moved it into a separate thread with a timeout. Now since I don't own the icon loader crate, I can't prevent that. But the daemon will not hang there.

**Comment by GallowsDove** [comment]
Recording of the weird freeze.

https://github.com/user-attachments/assets/236080b7-a286-4411-b123-aa5884dbc94a

**Comment by GallowsDove** [comment]
> The freeze happens when the icon loader hangs. I moved it into a separate thread with a timeout. Now since I don't own the icon loader crate, I can't prevent that. But the daemon will not hang there.

Weird that it's happening even when there are no icons in the notification

**Comment by Dr-42** [comment]
Exactly, in fact if there is an icon, then the loader doesn't hang. Only if there is an app_name, but there is no icon for icon_loader to load, the function just hangs. I don't understand what causes this, I even read the source code and found nothing.

**Comment by GallowsDove** [comment]
> in fact if there is an icon, then the loader doesn't hang

That's not true, I can see the same delay whether there is an icon or not

**Comment by Dr-42** [comment]
I see. But now I guess this much will work just fine.
