### ISSUE TITLE
Flickering when closing notifications

### ISSUE THREAD

**Issue by GallowsDove** [Dr-42/end-rs#6]
## Problem

When a notification is closed, the notification window (by default `notification-frame`) flickers

After some investigation, this is caused by calling 'eww open notification-frame' even when it's opened already.

The following eww wrapper script fixes the issue: 
```bash
if [ "$1" == "open" ]; then
  eww active-windows | grep "$2: $2" || eww open $2
else
  eww "$@"
fi
```

### Only open window when the first notification is added
This solution is possible, however it could run into issues when eww daemon is killed with `eww kill`. In this case, if there is a notification without timeout, it never expires and the window doesn't get opened without manual intervention via `eww open`.

### Check if it's already open, and only open it if it isn't
Would require extra call to `eww active-windows` every time notifications get updated, however it wouldn't run into the issues described above

I'd be willing to open PR on either of these. Let me know what you think.

**Comment by Dr-42** [comment]
I think polling with eww-active-windows is the better choice since I would like to keep os level shell piping to a minimum in the codebase as it makes it harder to read and maintain later on. Plus it also would run into the eww kill issue. Send the pr so that I can look into it.
